# Generated by Django 3.1.5 on 2021-07-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug_category',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
